version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Xamarin.AndroidX.Core
    versions:
    - 1.3.2.2
  - dependency-name: MSBuild.Sdk.Extras
    versions:
    - 3.0.23
  - dependency-name: Microsoft.NETCore.UniversalWindowsPlatform
    versions:
    - 6.2.11
