namespace XPlat.Foundation
{
    /// <summary>Represents a method that handles general events.</summary>
    /// <typeparam name="TSender">The object type.</typeparam>
    /// <typeparam name="TResult">The type of event data generated by the event.</typeparam>
    /// <param name="sender">The event source.</param>
    /// <param name="args">The event data. If there is no event data, this parameter will be null.</param>
    public delegate void TypedEventHandler<in TSender, in TResult>(TSender sender, TResult args);
}