namespace XPlat.API.Foundation
{
    /// <summary>
    /// Defines a method that handles general events.
    /// </summary>
    /// <param name="sender">
    /// The event source.
    /// </param>
    /// <param name="args">
    /// The event data. If there is no event data, this parameter will be null.
    /// </param>
    /// <typeparam name="TSender">
    /// The type of sender object.
    /// </typeparam>
    /// <typeparam name="TResult">
    /// The type of event data generated by the event.
    /// </typeparam>
    public delegate void TypedEventHandler<in TSender, in TResult>(TSender sender, TResult args);
}